export enum CategoryType {
  Housing = "Housing",
  Transportation = "Transportation",
  Food = "Food",
  HealthAndWellness = "Health & Wellness",
  PersonalCare = "Personal Care",
  Entertainment = "Entertainment",
  ClothingAndAccessories = "Clothing & Accessories",
  Education = "Education",
  Travel = "Travel",
  FamilyAndChildren = "Family & Children",
  GiftsAndDonations = "Gifts & Donations",
  Insurance = "Insurance",
  DebtRepayment = "Debt Repayment",
  SavingsAndInvestments = "Savings & Investments",
  BillsAndSubscriptions = "Bills & Subscriptions",
  Miscellaneous = "Miscellaneous",
  Income = "Income",
}
